language: php

php: ["7.0", "7.1", "7.2", "7.3", "7.4", "8.0"]

addons:
  apt:
    packages:
      - poppler-utils

env:
  global:
    - BUILD_COVERAGE_PHP_VERSION="8.0"
    - BUILD_PHAR_PHP_VERSION="8.0"
    - BUILD_PHAR_OUTPUT="build/cfditopdf.phar"
    - XDEBUG_MODE=coverage

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer install --no-progress --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs -sp bin/ src/ tests/ bin/ templates/
  - vendor/bin/php-cs-fixer fix --using-cache=no --dry-run --verbose
  - |
    if [[ $TRAVIS_PHP_VERSION == $BUILD_COVERAGE_PHP_VERSION ]]; then
      php -d zend_extension=xdebug.so vendor/bin/phpunit --testdox --coverage-clover=build/coverage.xml
    else
      vendor/bin/phpunit --testdox
    fi
  - | # do not run on phpstan on PHP 7.0 because it fail with array annotations
    if [[ $TRAVIS_PHP_VERSION != "7.0" ]]; then
      vendor/bin/phpstan analyse --no-progress --level max src/ tests/ bin/
    fi
  # build phar
  - |
    if [[ $TRAVIS_PHP_VERSION == $BUILD_PHAR_PHP_VERSION ]]; then
      rm -f "${BUILD_PHAR_OUTPUT}"
      bash development/build-phar "${BUILD_PHAR_OUTPUT}"
      test -f "${BUILD_PHAR_OUTPUT}"
    fi

after_script:
  # upload test covegare to scrutinizer
  - |
    if [[ $TRAVIS_PHP_VERSION == $BUILD_COVERAGE_PHP_VERSION ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml
    fi

deploy:
  provider: releases
  api_key:
    secure: V++o2L8UWr9GLicxWDnT3JFf+VnbxAAbkd1py8y14ISar7XzgfJ4A06KvwvQz2CYZpeHNeG3fakl4HyFuVl/cU+UxZtMAgMTpQs7d33pTpaFSKT8eOesNJQzRqhLr8PDUy6zAoDz+gNjMs7laQqh4PhK9+DoM2+EReno86pWqo6uWdSrv+PNYmIHObrWkAKJo4eZcmCV+4BnpVKmcuyKqYvXaTfSF3gPqZMsByGYn7jitiVu/9/t004BIlahXh0oTj8dpvNEUyWg2LTIa88PrlI6MFrS9vBs+4FVBrElxZxNWTtY/vj3FkDuxn84Yjn9s3q+6pinbmM4240O95VVU/qhlrdsx0RDAfgxZ+yH7fx8aD9zcrVG7tD7FuwgIbTUEJxTj0TBlQIB7zkxDoIygxvBqLgpPQ+/8TjCsja0fwqmrbfB6t2MtgJtLFBc5tAFaHeKkky5FvrR2fJaDg8WzsFR70pLbTqQ8BXjkiXIMKLV2NxQaPpbvlBis/Jq9oa39zy9W2OQB6OJs+2xPIL46mw3W5ZANpste4sUPdalx2vTA+gOrokEKYvzkoSf0zJAjGpO8D0PEObtc/AOybpfgFcXFQ15HiA4U65tdgOEZwmrRRzm/kAa8TewP3KaYM3BaEZvz9+3XP2bZuHLfJdjhiWmBoxFkC4opiLVAUoQ3N0=
  skip_cleanup: true
  file: "${BUILD_PHAR_OUTPUT}"
  on:
    repo: phpcfdi/cfditopdf
    condition: $TRAVIS_PHP_VERSION == $BUILD_PHAR_PHP_VERSION
    tags: true

notifications:
  email: false
